### ISSUE TITLE
typo in environment creation

### ISSUE THREAD

**Issue by benjaminirving** [leriomaggio/deep-learning-keras-euroscipy2016#1]
Great looking tutorial. Just a small typo in the environment setup of `README.md`. 

`conda create env ... ` should be `condo env create ...`

**Comment by leriomaggio** [comment]
Fixed! Thanks a lot 👍

**Comment by benjaminirving** [comment]
Great. Also in the `README.md` file here:
https://github.com/leriomaggio/deep-learning-keras-euroscipy2016#recreate-the-conda-environment
